name: mellow_auth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-218.0.dev

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  firebase_core: ^3.4.1
  shared_preferences: ^2.3.2
  cosmosdb: ^0.0.4
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
